name: McNully Co.
markdown: redcarpet
pygments: true
author: Peyton McNully
description: "Process and Technology Architects"
keywords: "apps, technology, iOS, Android, development, turnaround, consultant, fixer"